# Generated by Django 3.0.2 on 2020-06-22 10:53

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='images/photo_group', verbose_name='Изображение')),
                ('year_of_found', models.DateField(blank=True, null=True, verbose_name='Дата основания')),
                ('text', models.TextField(help_text='Введите информацию об артисте', max_length=10000, verbose_name='Информация')),
                ('vklink', models.CharField(help_text='ВК ссылка на артиста', max_length=100, verbose_name='Ссылка на вк')),
                ('websitelink', models.CharField(help_text='Ссылка на сайт артиста', max_length=100, verbose_name='Веб-сайт')),
                ('LPRname', models.CharField(help_text='Имя ЛПР (менеджер, директор и т.д.', max_length=100, verbose_name='Имя ЛПР')),
                ('role', models.CharField(blank=True, help_text='Должность', max_length=50, verbose_name='Должность')),
                ('LPRphone', models.CharField(help_text='Номер телефона ЛПР', max_length=13, verbose_name='Номер ЛПР')),
                ('LPRemail', models.EmailField(help_text='Email ЛПР', max_length=254, null=True, verbose_name='email ЛПР')),
                ('LPRlinkvk', models.CharField(help_text='ВК ссылка на ЛПР', max_length=100, verbose_name='Ссылка на вк ЛПР')),
                ('feedback', models.BooleanField(default=True, verbose_name='Форма обратной связи')),
                ('linkYandexM', models.CharField(blank=True, help_text='Ссылка на Яндекс.Музыка', max_length=100, verbose_name='Ссылка на Яндекс.Музыка')),
                ('linkGoogleP', models.CharField(blank=True, help_text='Ссылка на Google Music', max_length=100, verbose_name='Ссылка на Google Music')),
                ('linkAppleM', models.CharField(blank=True, help_text='Ссылка на Apple Music', max_length=100, verbose_name='Ссылка на Apple Music')),
                ('linkYoutubeM', models.CharField(blank=True, help_text='Ссылка на YouTube Music', max_length=100, verbose_name='Ссылка на YouTube Music')),
                ('linksite', models.CharField(blank=True, help_text='Ссылка на site', max_length=100, verbose_name='Ссылка на site')),
                ('linkvk', models.CharField(blank=True, help_text='Ссылка на VK', max_length=100, verbose_name='Ссылка на VK')),
                ('linkyoutube', models.CharField(blank=True, help_text='Ссылка на YouTube', max_length=100, verbose_name='Ссылка на YouTube')),
                ('linkinsta', models.CharField(blank=True, help_text='Ссылка на Instagram', max_length=100, verbose_name='Ссылка на Instagram')),
                ('linkfacebook', models.CharField(blank=True, help_text='Ссылка на Facebook', max_length=100, verbose_name='Ссылка на Facebook')),
            ],
            options={
                'verbose_name': 'артист',
                'verbose_name_plural': 'артисты',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(help_text='Город', max_length=60, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GenreName', models.CharField(help_text='Жанр', max_length=50, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', embed_video.fields.EmbedVideoField(help_text='Ссылка на видеозапись', verbose_name='Ссылка на видеозапись')),
                ('fk_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CatalogOfArtists.Artists')),
            ],
            options={
                'verbose_name': 'видеозапись',
                'verbose_name_plural': 'видеозаписи',
            },
        ),
        migrations.CreateModel(
            name='Relase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название релиза')),
                ('image', models.ImageField(blank=True, upload_to='images/photo_relases', verbose_name='Изображение')),
                ('age', models.CharField(max_length=4, verbose_name='Год выхода келиза')),
                ('fk_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CatalogOfArtists.Artists')),
            ],
            options={
                'verbose_name': 'релиз',
                'verbose_name_plural': 'релизы',
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/posters_artists', verbose_name='Изображение')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('fk_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CatalogOfArtists.Artists')),
            ],
            options={
                'verbose_name': 'афиша',
                'verbose_name_plural': 'афиша',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LPRname', models.CharField(help_text='Имя ЛПР (менеджер, директор и т.д.', max_length=100, verbose_name='Имя ЛПР')),
                ('role', models.CharField(blank=True, help_text='Должность', max_length=50, verbose_name='Должность')),
                ('LPRphone', models.CharField(help_text='Номер телефона ЛПР', max_length=13, verbose_name='Номер ЛПР')),
                ('LPRemail', models.EmailField(help_text='Email ЛПР', max_length=254, null=True, verbose_name='email ЛПР')),
                ('LPRlink', models.CharField(help_text='Cсылка на ЛПР', max_length=100, verbose_name='Ссылка ЛПР')),
                ('fk_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CatalogOfArtists.Artists')),
            ],
            options={
                'verbose_name': 'менеджмент',
                'verbose_name_plural': 'менеджмент',
            },
        ),
        migrations.CreateModel(
            name='Group_Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия, имя артиста')),
                ('role', models.CharField(max_length=50, verbose_name='Роль музыканта в группе')),
                ('fk_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CatalogOfArtists.Artists')),
            ],
            options={
                'verbose_name': 'состав',
                'verbose_name_plural': 'составы',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/gallery_artists', verbose_name='Изображение')),
                ('fk_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CatalogOfArtists.Artists')),
            ],
            options={
                'verbose_name': 'галерея',
                'verbose_name_plural': 'галерея',
            },
        ),
        migrations.AddField(
            model_name='artists',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CatalogOfArtists.Cities', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='artists',
            name='genre',
            field=models.ManyToManyField(help_text='Выберите жанры', related_name='genre', to='CatalogOfArtists.Genres', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='artists',
            name='main_genre',
            field=models.ForeignKey(help_text='Введите основной жанр', max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_genre', to='CatalogOfArtists.Genres', verbose_name='Основной жанр'),
        ),
    ]
