# Generated by Django 3.0.2 on 2020-07-17 20:08

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineMedia', '0002_auto_20200610_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='parts',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateField(help_text='Дата написания статьи', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.TimeField(help_text='Время написания статьи', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_img',
            field=models.ImageField(help_text='Картинка для статьи в списке', upload_to='images/article_img', verbose_name='Картинка'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', embed_video.fields.EmbedVideoField(help_text='Ссылка на видеозапись', verbose_name='Ссылка на видеозапись')),
                ('position', models.SmallIntegerField(default=0)),
                ('id_article', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OnlineMedia.Article', verbose_name='Статья')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=1000, verbose_name='Цитата')),
                ('quoter', models.TextField(max_length=100, verbose_name='Кто сказал')),
                ('position', models.SmallIntegerField(default=0)),
                ('id_article', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OnlineMedia.Article', verbose_name='Статья')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Параграф')),
                ('position', models.SmallIntegerField(default=0)),
                ('id_article', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OnlineMedia.Article', verbose_name='Статья')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Картинка', upload_to='images/article_img')),
                ('about', models.TextField(max_length=1000, verbose_name='Заголовок')),
                ('position', models.SmallIntegerField(default=0)),
                ('id_article', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OnlineMedia.Article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('position', models.SmallIntegerField(default=0)),
                ('id_article', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OnlineMedia.Article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовки',
            },
        ),
    ]
