# Generated by Django 3.0.2 on 2020-07-17 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('OnlineMedia', '0003_auto_20200717_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateField(auto_now_add=True, help_text='Дата написания статьи', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.TimeField(auto_now_add=True, help_text='Время написания статьи', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id_project',
            field=models.ForeignKey(blank=True, help_text='Идентификатор проекта', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id_section',
            field=models.ForeignKey(blank=True, help_text='Идентификатор категории', null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineMedia.Section', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='image',
            name='about',
            field=models.TextField(max_length=300, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='Параграф'),
        ),
    ]
