# Generated by Django 3.0.3 on 2020-07-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineMedia', '0004_auto_20200718_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraph',
            options={'verbose_name': 'Абзац', 'verbose_name_plural': 'Абзацы'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитаты'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(help_text='Полный текст статьи', max_length=3000, verbose_name='Текст'),
        ),
    ]
