# Generated by Django 3.0.2 on 2020-08-15 20:25

from django.db import migrations



def add_section(apps, schema_editor):
    section = apps.get_model('OnlineMedia', 'Section')
    section.objects.get_or_create(section_name="Статьи", section_name_eng="Articles")
    section.objects.get_or_create(section_name="События", section_name_eng="Events")
    section.objects.get_or_create(section_name="Меркетинг", section_name_eng="Marketing")
    section.objects.get_or_create(section_name="Авторские материалы", section_name_eng="Authors")
    section.objects.get_or_create(section_name="История рока", section_name_eng="Roсkhistory")


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineMedia', '0005_auto_20200720_1411'),
    ]

    operations = [
        migrations.RunPython(add_section),
    ]
